server:
  port: 8083
  servlet:
    context-path: /${spring.application.name}

radish:
  agent:
    ip: 192.168.140.146
    port: 8083
    name: tt
    logpath: /tmp/log/radish
    shpath: /tmp/log/radish
  scheduler:
    server: http://127.0.0.1:8888/radish-scheduing
  log-view-mode: servlet
  log-view-netty:
    port: 8084


spring:
  application:
    name: radish-agent
  profiles:
    active: dev
  datasource:
    # 以下对应druid数据源的配置
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      validation-query: SELECT 1 FROM DUAL
      pool-prepared-statements: true
      validationQueryTimeout: 5
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      max-open-prepared-statements: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: stat
#mybatis
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: org.sam.shen.agent.entity  # 注意：对应实体类的路径
  config-location: classpath:mybatis-config.xml

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

---

# 生产环境配置
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://??????/radish?useUnicode=true&characterEncoding=UTF-8
    username: ???
    password: ???
  redis:
    database: 3
    host: ???.???.???.???
    port: 6379
    password: pass
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0

---

# 开发环境配置
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.140.215:3306/radish?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 111111
  redis:
    database: 1
    host: 192.168.140.215
    port: 6379
    password: pass
    timeout: 3000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1s
        max-idle: 8
        min-idle: 0